### PR TITLE
Fix smb helm chart and instructions

### PR DESCRIPTION
**Pull request by teo-sonosim**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

The ability to perform an all-in-one helm installation is a fantastic feature implemented in #49 (shoutout: @snickell!), this PR adds minor fixes.

**Special notes for your reviewer**:

Tested working on an on-prem MiniKF (Minikube) installation.

### CODE REVIEW

**Comment by andyzhangx** [comment]
@snickell could you take a look? thanks

also there is a new release `1.0.3` here for all-in-one helm installation change:
```
mcr.microsoft.com/k8s/flexvolume/smb-flexvolume:1.0.3
```

**Comment by snickell** [comment]
hi @teo-sonosim! 

Could you explain the motivation in removing the selector? Removing the selector requires changing the command, and the resulting command is more complicated, and harder to understand. I generally try to keep "magic setup commands" as understandable as possible, so people aren't just doing black magic by rote ;-)

My understanding is that generally its considered a good idea for modern helm charts to include app.kubernetes.io/name and app.kubernetes.io/instance selectors anyway....

What version of kubectl are you using? I believe that most recent-ish versions support pod/NAME syntax.

**Comment by teo-sonosim** [comment]
Hey @snickell!

Note: everything below comes with an implicit "AFAIK"
> 
> Could you explain the motivation in removing the selector? Removing the selector requires changing the command, and the resulting command is more complicated, and harder to understand. I generally try to keep "magic setup commands" as understandable as possible, so people aren't just doing black magic by rote ;-)
> 
> My understanding is that generally its considered a good idea for modern helm charts to include app.kubernetes.io/name and app.kubernetes.io/instance selectors anyway....


Sure. I assumed that the **_PV_** selector section was a copy/paste typo from the **_PVC_** template as _selector_ doesn't seem to be a valid spec field for a **_PV_** (but of course is for a **_PVC_** and allows for all those benefits you mentioned). 

The exact error for reference: 
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(PersistentVolume.spec): unknown field selector in "io.k8s.api.core.v1.PersistentVolumeSpec"`

When removing that selector section, everything indeed worked like magic. What commands do you believe would need to be changed?


> 
> What version of kubectl are you using? I believe that most recent-ish versions support pod/NAME syntax.

This is a fair point, thanks for pointing it out. I did have an older version of kubectl (1.14). Using the latest kubectl version (1.18), the pod/NAME syntax does work.

**Comment by snickell** [comment]
@teo-sonosim I just checked a recent k8s spec, and you're absolutely right about not having a selector in the PersistentVolume being correct (and yeah, it doesn't logically make sense, I probbably did just copy/paste it from the volumeclaim wihtout looking closely enough!)

Would you be kind enough to revise the PR to keep the existing pod selection approach, but mention that a new-ish kubectl might fix problems following the README?

**Comment by teo-sonosim** [comment]
> Would you be kind enough to revise the PR to keep the existing pod selection approach, but mention that a new-ish kubectl might fix problems following the README?

@snickell Done! I noted the minimum kubectl version number compatible with that syntax in the README.

**Comment by andyzhangx** [comment]
would you take a look @snickell? thanks.

**Review by andyzhangx — APPROVED** [review]
/lgtm

**Pull request merged**
